// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ciutqdrbjduuunvtogda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpdXRxZHJiamR1dXVudnRvZ2RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTU1NzMsImV4cCI6MjA2MTM5MTU3M30.OtIm3MiT1t43gYW6CdiawQe_RcTS8OO1_d8DPd-j0vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);